const constants = {
  SORT_PRODUCT: "SORT_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  RATE_PRODUCT: "RATE_PRODUCT",
  REVIEW_PRODUCT: "REVIEW_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  SET_HISTORY: "SET_HISTORY"
 }
 export default constants