const constants = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
  CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
  RECEIVE_PRODUCTS: 'RECIEVE_PRODUCTS',
  CHECKOUT_FAILURE: 'CHECKOUT_FAILURE',
  SORT_PRODUCT: "SORT_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  CHOOSE_PRODUCT: 'CHOOSE_PRODUCT',
  RATE_PRODUCT: "RATE_PRODUCT",
  REVIEW_PRODUCT: "REVIEW_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  FETCH_REVIEWS: "FETCH_REVIEWS",
  FETCH_REVIEWS_PENDING: "FETCH_REVIEWS_PENDING",
  FETCH_REVIEWS_ERROR: "FETCH_REVIEWS_ERROR",
  SIZE_RATING: 'SIZE_RATING',
  FIT_RATINg: 'FIT_RATING',
  WIDTH_RATINg: 'WIDTH_RATING',
  COMFORT_RATING: 'COMFORT_RATING',
  QUALITY_RATING: 'QUALITY_RATING',
  LENGTH_RATING: 'LENGTH_RATING',
  ADD_NAME: 'ADD_NAME',
  NAV_TO_HOME: 'NAV_TO_HOME'
 }

export default constants