const constants = {
  SORT_PRODUCT: "SORT_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  RATE_PRODUCT: "RATE_PRODUCT",
  REVIEW_PRODUCT: "REVIEW_PRODUCT",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  SET_HISTORY: "SET_HISTORY",
  REVIEVE_REVIEWS: "RECIEVE_REVIEWS",
  FETCH_REVIEWS: "FETCH_REVIEWS",
  CHOOSE_PRODUCT: 'CHOOSE_PRODUCT',
  ADD_NAME: 'ADD_NAME'
 }
 module.exports = constants